from .random_agent import RandomAgent
from .human_agent import HumanAgent
from .student_agent import StudentAgent
from .greedy_corners_agent import StudentAgent
from .best_agent import BestAgent
from .mcts_agent import StudentAgent
from .old_student import StudentAgent
from .class_agent import StudentAgent
from .cat import StudentAgent
